### ISSUE TITLE
Three suggestions

### ISSUE THREAD

**Issue by rauschma** [ericdouglas/ES6-Learning#14]
Great list of resources! Three suggestions:

* This is the most current version of my talk on ES6, you can remove the others: http://www.2ality.com/2015/02/using-es6-today-minsk.html
* If a section gets too long, I’d group the items in some manner (e.g. by topic). It may also make sense to mention the author each time, esp. in the “articles” section.
* Shim used by Babel: https://github.com/zloirock/core-js

**Comment by ericdouglas** [comment]
@rauschma thanks for the suggestions! I will update the list!

:smile:

**Comment by rauschma** [comment]
Your work is much appreciated! There will always be more resources, so I think it is better to worry about quality than about quantity (long lists can overwhelm people).

**Comment by ericdouglas** [comment]
I completely agree with you! I'll improve the list with your suggestions!

**Comment by ericdouglas** [comment]
Closing this topic. Suggestions implemented. :smile: 

**ps**: WIP with articles [here](https://github.com/ericdouglas/ES6-Learning/issues/27)
