### ISSUE TITLE
Dead link: Rewriting A WebApp With ECMAScript 6

### ISSUE THREAD

**Issue by keradus** [ericdouglas/ES6-Learning#16]

**Comment by ericdouglas** [comment]
Many thanks @keradus ! I fixed the link! :smile:

**Comment by keradus** [comment]
Great job!

**Comment by keradus** [comment]
Some offtop question @ericdouglas , could you suggest any good IDE that has support for ECMA6 and is not WebStorm ?

**Comment by ericdouglas** [comment]
I don't know @keradus , sorry.

**Comment by keradus** [comment]
I see. Thank you ;)
