### ISSUE TITLE
Add "ES6 Overview in 350 Bullet Points"?

### ISSUE THREAD

**Issue by ThomasG77** [ericdouglas/ES6-Learning#29]
As I didn't know the best place to put this resource, I would like a feedback about adding
 [ES6 Overview in 350 Bullet Points](https://ponyfoo.com/articles/es6) to the repo.

**Comment by ericdouglas** [comment]
@ThomasG77 we can add this in the "Articles & Tutorials" section :smile:

**Comment by ericdouglas** [comment]
@ThomasG77 do you want to send a PR to include this article?

**Comment by ThomasG77** [comment]
Done in PR #32
