### ISSUE TITLE
Add 'learn ECMAScript 6 basics in simple terms'?

### ISSUE THREAD

**Issue by imalitavakoli** [ericdouglas/ES6-Learning#33]
You have gathered an awesome list of resources for learning ES6. So I was wondering what about adding this repo too?
https://github.com/imalitavakoli/learn-es6

It actually helps beginners to get started with ES6 and explains it in simple terms :smiley:

**Comment by ericdouglas** [comment]
@imalitavakoli thank you! Interesting material :+1:
