### ISSUE TITLE
Course: "Expert ES6 - Tagtree" is unavailable

### ISSUE THREAD

**Issue by dualcyclone** [ericdouglas/ES6-Learning#35]
The Expert ES6 course seems to have been removed from Tagtree:

http://tagtree.io/courses/expert-es6

But they do have a whole bunch of ES6 Videos:

http://tagtree.io/ecmascript-6-episode-1
http://tagtree.io/ecmascript-6-episode-2
http://tagtree.io/ecmascript-6-episode-3
http://tagtree.io/ecmascript-6-episode-4
http://tagtree.io/ecmascript-6-let
http://tagtree.io/es6-proxies

**Comment by ericdouglas** [comment]
@dualcyclone thank you! :smile:
