### ISSUE TITLE
some links are broken

### ISSUE THREAD

**Issue by rohan-paul** [ericdouglas/ES6-Learning#55]
Few links are broken - 

[Say Hello to ES2015](https://tutor.mantrajs.com/say-hello-to-ES2015/introduction)
[The JavaScript Show - Ecmascript 6](http://castroller.com/podcasts/TheJavascriptShow/2880479)
[The JavaScript Show - Ecmascript 6](http://castroller.com/podcasts/TheJavascriptShow/2880479)

**Comment by ericdouglas** [comment]
@rohan-paul thanks!
