### ISSUE TITLE
Broken links report

### ISSUE THREAD

**Issue by mitsuruog** [ericdouglas/ES6-Learning#7]
broken links report.

* Articles & Tutorials
  * 4. [Javascript ES6: Learn important features in a few minutes](http://www.frontendjournal.com/javascript-es6-learn-important-features-in-a-few-minutes/) -> 503
  * 12. [ECMAScript 6 features: classes](http://dstrunk.com/ecmascript-6-features-classes/) -> 502
* More Useful Links
  * 7. [ES.next needs You!](http://javascriptweblog.wordpress.com/2012/05/07/putting-the-developer-back-in-es-next/) -> 404

Thanks :)

**Comment by ericdouglas** [comment]
Thanks again @mitsuruog !
